### ISSUE TITLE
How to Post to Server via A6C / A20 ?

### ISSUE THREAD

**Issue by k30r88** [stefanwendelmann/HorseCam#1]
Hi @stefanwendelmann , I went thru your .ino file, and I did not see AT+CAMPOST command to post picture to the server, can you provide us guidance how to post to server using A6C/A20 device ?

**Comment by stefanwendelmann** [comment]
Sadly i didnt had the time to get the projekt forward.
But here is a "Silver Lining" for your Problem.

See the https://github.com/stefanwendelmann/HorseCam/blob/master/A6C%20Documents/upload%20photo%20server.rar there is a txt file with the AT+CAMPOST 

You can further see the commandlist in the PDF  安信可A5_A6_A7_A6C_A20模组用户开发手册20170208.pdf in the same folder as the rar.

Just use a translator of your choice to translate it to your lang,

Hope i could help you with that.

**Comment by k30r88** [comment]
Thanks @stefanwendelmann for your information.
